name: Post to Slack using Google Secrets

on:
  push:
  workflow_call:
    inputs:
      CHANNEL_ID:
        required: true
        type: string
      TEXT:
        required: true
        type: string
      GOOGLE_CREDENTIALS_JSON:
        required: true
        type: string
      SLACK_TOKEN:
        required: true
        type: string
      BLOCKS:
        required: false
        type: string

jobs:
  post_to_slack_google_secret:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
    # Checkout Code
    - name: Checkout code
      uses: actions/checkout@v3
    # Authorize with passed in secret key using compositing (github secret key interpolated)
    - name: Auth with GCP
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{github.event.inputs.GOOGLE_CREDENTIALS_JSON}}'
    - name: Fetch secret from Google Secrets to deploy message using slack
      id: google_deploybot_secret
      uses: 'google-github-actions/get-secretmanager-secrets@v0'
      with:
        secrets: |-
          slack_token:@{{ github.event.inputs.SLACK_TOKEN }}
    - name: Post to slack channel with only text
      uses: slackapi/slack-github-action@v1.21.0
      with:
        channel-id: CHANNEL_ID
        slack-message: TEXT
      env:
        SLACK_BOT_TOKEN: '${{ steps.google_deploybot_secret.outputs.slack_token }}'