name: Post to slack with token from google secrets

on:
  workflow_call:
    inputs:
      CHANNEL_ID:
        required: true
        type: string
        description: Channel ID for slack message to be sent to
      TEXT:
        required: true
        type: string
        description: Simple text message sent with Slack message
      WORKLOAD_IDENTITY_PROVIDER:
        required: true
        type: string
        description: Identity Provider
      SERVICE_ACCOUNT:
        required: false
        type: string
        description: Service account
      GOOGLE_SECRET_KEY_FOR_SLACK_TOKEN:
        required: false
        type: string
        description: Name of secret key to grab token from to post to Slack
jobs:
  post_to_slack_google_secret:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    # Authorize with passed in GOOGLE CREDENTIAL JSON
    - name: Auth with GCP
      uses: 'google-github-actions/auth@v0'
      with:
        create_credentials_file: true
        workload_identity_provider: '${{ inputs.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ inputs.SERVICE_ACCOUNT }}'
    # Retrieve secret from Google Secrets using
    - name: Fetch secret from Google Secrets to deploy message using slack
      id: google_secret
      uses: 'google-github-actions/get-secretmanager-secrets@v0'
      with:
        secrets: |-
            slack_token:${{ inputs.GOOGLE_SECRET_KEY_FOR_SLACK_TOKEN }}
    # Use slack token that is retrieved from google secrets to post to slack
    - name: Post to slack channel with only text
      if: "github.event.inputs.BLOCKS == ''"
      uses: slackapi/slack-github-action@v1.21.0
      with:
        channel-id: "${{ inputs.CHANNEL_ID }}"
        slack-message: ${{ inputs.TEXT }}
      env:
        SLACK_BOT_TOKEN: '${{ steps.google_secret.outputs.slack_token }}'
    - name: Post to slack channel with blocks
      if: "inputs.BLOCKS != ''"
      uses: slackapi/slack-github-action@v1.21.0
      with:
        channel-id: ${{ inputs.CHANNEL_ID }}
        slack-message: ${{ inputs.TEXT }}
        payload: |
          {
            "text": "${{ inputs.TEXT }}",
            "blocks": ${{ inputs.BLOCKS }}
          }
      env:
        SLACK_BOT_TOKEN: '${{ steps.google_secret.outputs.slack_token }}'