name: Test workflow

on:
  push:
  workflow_call:
    inputs:
      CHANNEL_ID:
        required: true
        type: string
        description: Channel ID for slack message to be sent to
      TEXT:
        required: true
        type: string
        description: Simple text message sent with Slack message
      GOOGLE_CREDENTIALS:
        required: true
        type: string
        description: Encoded JSON string that represent google credential service account that has access to the secret defined by GOOGLE_SECRET_KEY_FOR_SLACK_TOKEN
      GOOGLE_SECRET_KEY_FOR_SLACK_TOKEN:
        required: true
        type: string
        description: Fully qualified secret key [project_id]/[key_name]
      BLOCKS:
        required: false
        type: string
        description: Encoded JSON string outlined here https://api.slack.com/reference/block-kit/blocks 
jobs:
  post_to_slack_google_secret:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
    # Authorize with passed in GOOGLE CREDENTIAL JSON
    - name: Auth with GCP
      uses: HausAnalytics/actions/.github/workflows/post_to_slack_google_secret.yml@f-slack
      with:
        CHANNEL_ID: '${{ github.event.inputs.CHANNEL_ID }}'
        TEXT: '${{ github.event.inputs.TEXT }}'
        GOOGLE_CREDENTIALS: '${{ github.event.inputs.GOOGLE_CREDENTIALS }}'
        GOOGLE_SECRET_KEY_FOR_SLACK_TOKEN: '${{ github.event.inputs.GOOGLE_SECRET_KEY_FOR_SLACK_TOKEN }}'
        BLOCKS: '${{ github.event.inputs.BLOCKS }}'