name: Test post to slack with token from google secrets

on:
  push


jobs:
  test_post_to_slack:
    uses: HausAnalytics/actions/.github/workflows/post_to_slack_google_secret.yml@f-slack
    secrets: inherit
    with:
      CHANNEL_ID: "@jeremy"
      TEXT: "From Test File"
