name: Test post to slack with token from google secrets

on:
  push


jobs:
  test_post_to_slack_with_text:
    uses: HausAnalytics/actions/.github/workflows/post_to_slack_google_secret.yml
    secrets: inherit
    with:
      CHANNEL_ID: "@jeremy"
      TEXT: "From Test File"
  test_post_to_slack_with_blocks:
    uses: HausAnalytics/actions/.github/workflows/post_to_slack_google_secret.yml
    secrets: inherit
    with:
      CHANNEL_ID: "@jeremy"
      TEXT: "From Test File"
      BLOCKS: '[{"type":"section","text":{"type":"mrkdwn","text":"test text"}}]'
